language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t singhabhinav/docker-react-dev -f Dockerfile.dev .
script:
    - docker run -e CI=true singhabhinav/docker-react-dev npm run test
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket-name: "elasticbeanstalk-us-west-2-034275272121"
    bucker-path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"